### ISSUE TITLE
UDV vs. udv

### ISSUE THREAD

**Issue by stephens999** [stephenslab/fastglmpca#3]
I suggest using u,d and v, with d a vector, for consistency with svd

**Comment by pcarbo** [comment]
@eweine I'll take care of this.

**Comment by pcarbo** [comment]
For reference:

```r
svd(matrix(rnorm(16),4,4))
# $d
# [1] 2.6676 2.5212 1.6887 0.4364
# $u
#         [,1]    [,2]    [,3]      [,4]
# [1,] -0.4854 -0.5954 -0.5070 -0.390954
# [2,] -0.3947  0.6504  0.1077 -0.640022
# [3,] -0.3950 -0.3843  0.8344 -0.006513
# [4,]  0.6727 -0.2736  0.1873 -0.661427
# $v
#          [,1]    [,2]     [,3]    [,4]
# [1,] -0.06341 -0.7447 -0.11430 -0.6545
# [2,] -0.47001  0.5554 -0.46402 -0.5053
# [3,]  0.34895 -0.1602 -0.87293  0.3009
# [4,] -0.80827 -0.3337 -0.09807  0.4751
```

**Comment by pcarbo** [comment]
@stephens999 It turns out not to be quite so simple to make `fastglmpca` consistent with `svd`. I changed the output `D` to `d` (now it is a vector). However, renaming the other outputs is complicated by the fact that `U` and `V` may also be *inputs* to other fuuntions, and the capital letters are helpful throughout as a convention for inputs and outputs that are matrices. So, for internal consistency, it is better to have the outputs be `U`, `V`, `d`.
